# Generated by Django 3.2.1 on 2021-12-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0002_alter_employeebank_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='in_stock_total',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='mfg_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='shelf_no',
        ),
    ]
