# Generated by Django 3.2.1 on 2021-12-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0003_auto_20211212_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='buy_price',
            field=models.CharField(default='0000000', max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sell_price',
            field=models.CharField(default='0000000', max_length=255),
        ),
    ]
