# Generated by Django 3.2.1 on 2021-12-12 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0004_auto_20211212_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='inventory',
            name='in_stock_total',
            field=models.IntegerField(default='000'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='mfg_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
