# Generated by Django 3.2.1 on 2021-12-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0005_auto_20211212_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='expire_date',
            field=models.DateField(default='2014-02-09'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='mfg_date',
            field=models.DateField(default='2014-02-09'),
        ),
    ]
