# Generated by Django 3.2.1 on 2021-12-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0006_auto_20211212_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='buy_price',
            field=models.CharField(default='000', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sell_price',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
