# Generated by Django 3.2.1 on 2021-12-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0007_auto_20211212_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='mfg_date',
        ),
    ]
