# Generated by Django 3.2.1 on 2021-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0008_auto_20211212_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='expire_date',
            field=models.DateField(default='2014-02-09'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='mfg_date',
            field=models.DateField(default='2014-02-09'),
        ),
    ]
