# Generated by Django 3.2.1 on 2021-12-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0009_auto_20211212_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='in_stock_total',
            field=models.IntegerField(default=0),
        ),
    ]
