# Generated by Django 3.2.1 on 2021-12-14 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0011_auto_20211213_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaccount',
            name='transaction_type',
        ),
    ]
