# Generated by Django 3.2.1 on 2021-12-14 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0012_remove_companyaccount_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaccount',
            name='added_on',
        ),
    ]
