# Generated by Django 3.2.1 on 2021-12-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagement', '0013_remove_companyaccount_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequest',
            name='prescription',
        ),
    ]
